"""
Repository interfaces (ports) that the application layer depends on.
"""
from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.infrastructure.db.models.document import Document
from app.infrastructure.db.models.document_version import DocumentVersion
from app.infrastructure.db.models.refresh_token import RefreshToken
from app.infrastructure.db.models.user import User
from app.infrastructure.db.models.workspace import Workspace


class UserRepositoryInterface(Protocol):
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def create(self, *, email: str, password_hash: str, full_name: str | None) -> User: ...


class RefreshTokenRepositoryInterface(Protocol):
    async def create(self, *, user_id: UUID, token_hash: str, expires_at: datetime) -> RefreshToken: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, refresh_token: RefreshToken) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...


class WorkspaceRepositoryInterface(Protocol):
    async def create(self, *, owner_id: UUID, name: str) -> Workspace: ...
    async def get_by_id(self, workspace_id: UUID) -> Workspace | None: ...
    async def list_by_owner(self, owner_id: UUID, *, include_trashed: bool = False) -> list[Workspace]: ...
    async def update(self, workspace: Workspace, **fields) -> Workspace: ...
    async def soft_delete(self, workspace: Workspace) -> Workspace: ...


class DocumentRepositoryInterface(Protocol):
    async def create_document(self, *, workspace_id: UUID, title: str, source_type: str) -> Document: ...
    async def get_document_by_id(self, document_id: UUID) -> Document | None: ...
    async def list_documents(self, workspace_id: UUID) -> list[Document]: ...
    async def get_next_version_number(self, document_id: UUID) -> int: ...
    async def create_version(self, **kwargs) -> DocumentVersion: ...
    async def list_versions(self, document_id: UUID) -> list[DocumentVersion]: ...
    async def get_current_version(self, document_id: UUID) -> DocumentVersion | None: ...